services:
  db:
    image: mysql
    container_name: capstone
    restart: no
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/sql/init-data.sql:/docker-entrypoint-initdb.d/2-init-data.sql
    env_file:
      - .env.properties
    ports:
      - 3306:3306
    profiles: [ database ]