services:
  db:
    image: mysql
    container_name: capstone
    restart: no
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/sql/provinces.sql:/docker-entrypoint-initdb.d/2-provinces.sql
      - ./src/main/resources/sql/districts.sql:/docker-entrypoint-initdb.d/3-districts.sql
      - ./src/main/resources/sql/cinema.sql:/docker-entrypoint-initdb.d/4-cinema.sql
      - ./src/main/resources/sql/cinema-province.sql:/docker-entrypoint-initdb.d/5-cinema-province.sql
      - ./src/main/resources/sql/branch.sql:/docker-entrypoint-initdb.d/6-branch.sql
    env_file:
      - .env.properties
    ports:
      - 3306:3306
    profiles: [ database ]