spring:
  config:
    import: optional:file:.env.properties
  application:
    name: booking-ticket-cinema-be
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${MYSQL_URL}/${MYSQL_DATABASE}?allowMultiQueries=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      default-media-type: application/json
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  key: bCXUiu8ML78+HkgDMp97NB1hNnrE0BQBJszpGzttbqd0r+kmCR1XbQwg6fGKh09vTE5wO9teRM4KZBb1QByDGw==
  expirationMs: 5 * 60 * 1000
cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    region: ${R2_REGION}
    endpoint: ${R2_ENDPOINT}
    bucket: ${R2_BUCKET}
    public-path: ${R2_PUBLIC_PATH}