server:
  port: ${SERVER_PORT}
spring:
  application:
    name: booking-ticket-cinema-be
  profiles:
    active: @spring.profile.active@
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${MYSQL_URL}/${MYSQL_DATABASE}?allowMultiQueries=true
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      default-media-type: application/json
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write-date-keys-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  key: RWy4_RjrkCv8j4qGN4sThqZDJlNgjtivkD8dCZ5yodCSohS9LCzYAsIdd62EWD7qupjeQ0AxAKKQJuPHLWivSA
  expirationMs: 28800000 # 8*60*60*1000
cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    region: ${R2_REGION}
    endpoint: ${R2_ENDPOINT}
    bucket: ${R2_BUCKET}
    public-path: ${R2_PUBLIC_PATH}
open:
  api:
    title: ${OPEN_API_TITLE}
    version: ${OPEN_API_VERSION}
    description: ${OPEN_API_DESCRIPTION}
    serverUrl: ${OPEN_API_SERVER_URL}
    serverName: ${OPEN_API_SERVER_NAME}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: "Authentication,User,Profile,District,Province,Cinema,Branch,Hall,Screening,Movie,Reservation,Seat,Upload,Minimal"
    operations-sorter: method
logging:
  level:
    org.jooq: DEBUG
    org.springframework: DEBUG
---
Spring:
  profiles:
    active: dev
  config:
    import: optional:file:dev.env.properties
---
Spring:
  profiles:
    active: test
  config:
    import: optional:file:test.env.properties